name: CI Workflow

on:
  push:
    branches:
      - main  # Runs the workflow when code is pushed to the main branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # Specifies the OS for the runner

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3  # Fetches the latest code

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # You can specify the required Node.js version

      - name: Install dependencies
        run: npm install  # Installs project dependencies

      - name: Run tests
        run: npm test  # Executes the test suite
